### ISSUE TITLE
Interfaces rules

### ISSUE THREAD

**Issue by mdenisenko** [WordPress/WordPress-Coding-Standards#1868] opened 2020-02-19 07:25 UTC
I have interface Storage.

1. What should WPCS interfaces be called?

- IStorage
- I_Storage
- InterfaceStorage
- Interface_Storage
- StorageInterface
- Storage_Interface.

2. What should be called file names for interfaces?

- interface-storage

**Comment by dingo-d** [comment] 2020-02-19 07:28
We don't have an agreement about this atm.

Related: #1327, #1859

**Comment by jrfnl** [comment] 2020-02-19 08:19
Closing as a duplicate of #1859. Please continue the discussion there.

**Closed by jrfnl** 2020-02-19 08:19 UTC
Labels: Status: Duplicate
