### ISSUE TITLE
Possibility to add class method as a sanitized function

### ISSUE THREAD

**Issue by 9brada6** [WordPress/WordPress-Coding-Standards#1873] opened 2020-03-18 13:53 UTC
## Is your feature request related to a problem?
✔ If I try to add a function that sanitize my input -> works, without a question.
❌ If I try to add a static method or just a simple class method -> it will not work(Maybe there is a possibility, but I can't find an example).

## Describe the solution you'd like
Possibility to add in config class methods to sanitize inputs, something like:
```
<rule ref="WordPress.Security.ValidatedSanitizedInput">
    <properties>
        <property name="customUnslashingSanitizingFunctions" type="array">
            <element value="sanitize_field"/><!-- This works, other 3 don't -->
            <element value="MY_Custom_Class::sanitize_field"/>
            <element value="MY_Custom_Class->sanitize_field"/>
            <element value="array(MY_Custom_Class, sanitize_field)"/>
        </property>
    </properties>
</rule>

<rule ref="WordPress.Security.NonceVerification">
    <properties>
        <property name="customUnslashingSanitizingFunctions" type="array">
            <element value="sanitize_field"/><!-- This works, other 3 don't -->
            <element value="MY_Custom_Class::sanitize_field"/>
            <element value="MY_Custom_Class->sanitize_field"/>
            <element value="array(MY_Custom_Class, sanitize_field)"/>
        </property>
    </properties>
</rule>
```

**Comment by jrfnl** [comment] 2020-03-18 15:23
Thanks for reporting this, but there's an open feature request for this already.

Closing as duplicate of #413

**Closed by jrfnl** 2020-03-18 15:23 UTC
