### ISSUE TITLE
An error occurred during processing; checking has been aborted.

### ISSUE THREAD

**Issue by web-programmer-here** [WordPress/WordPress-Coding-Standards#2205] opened 2023-02-15 18:08 UTC
## Bug Description
When running the phpcs, I keep getting this error: 

```
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: trim(): Passing null to
   |       | parameter #1 ($string) of type string is deprecated in
   |       | .../vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WP/I18nSniff.php
   |       | on line 194 (Internal.Exception)
```

## Error Code
Error code is coming from I18nSniff.php

## Environment
PHP 8.2.2
PHP_CodeSniffer version 3.7.1 
Composer version 2.4.1

**Comment by jrfnl** [comment] 2023-02-15 19:28
Closing as duplicate of something which was fixed a while back. Please search the issues in the repo before opening an issue.

**Closed by jrfnl** 2023-02-15 19:28 UTC
Labels: Status: Duplicate, Status: Invalid

**Comment by web-programmer-here** [comment] 2023-02-15 21:20
@jrfnl Thank you, I used develop branch and the error is gone
