### ISSUE TITLE
Report error for incomplete translators comments

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2007] opened 2021-08-18 08:22 UTC
## Is your feature request related to a problem?

```
// translators: %1$s: world
_e( 'hello %1$s and %2$s', 'demo' ); 
```

=> translators comment is missing %2$s

Also give an error, if the translators comment has more placeholders than the actual string.

## Describe the solution you'd like

Error: "Mismatch between placeholders in translators comment and the actual string. Please make sure you use the same number and type of placeholders in both"

**Comment by swissspidy** [comment] 2021-08-18 09:24
For context, this was originally filed at https://github.com/wp-cli/i18n-command/issues/279

`I18nSniff:: check_for_translator_comment()` currently only checks for the presence of a translators comment if one of the text strings contains a placeholder, but it does not check whether the placeholders are adequately described.

For the case above, WordPress core uses the following style:

```php
// Incorrect:

// translators: %1$s: John
_e( 'hello %1$s and %2$s', 'demo' ); 


// Incorrect:

// translators: %1$s: John %2$s: Jane
_e( 'hello %1$s and %2$s', 'demo' ); 


// Correct:

// translators: 1: John. 2: Jane.
_e( 'hello %1$s and %2$s', 'demo' ); 
```

Enforcing a specific style (`1: John. 2: Jane.` vs `%1$s: John %2$s: Jane`) could be considered to be out of scope, but I think it's well established in the WordPress ecosystem and `1: John. 2: Jane.` is the format most commonly encountered by translators.

**Comment by kkmuffme** [comment] 2021-08-18 12:04
>Enforcing a specific style (1: John. 2: Jane. vs %1$s: John %2$s: Jane) could be considered to be out of scope, but I think it's well established in the WordPress ecosystem and 1: John. 2: Jane. is the format most commonly encountered by translators.

I would stick with the more common standard of %s/%1$s,... as this is used outside of WP too, whereas the 1:, 2: is more of a WP thing, that is not adhered to by most of WP plugins either (most use %1$s in translators comments)

**Comment by jrfnl** [comment] 2021-08-18 13:18
I have a feeling this is basically a duplicate of #1229. Please confirm and if so, let's keep the conversation in the original ticket.

**Comment by swissspidy** [comment] 2021-08-18 13:50
It does sound like a duplicate indeed 👍

**Comment by jrfnl** [comment] 2021-08-18 14:23
@swissspidy Thanks for confirming. I will close this issue in that case, though with the issue mention, they are now linked together so whenever this gets solved all information is available.

**Closed by jrfnl** 2021-08-18 14:23 UTC
Labels: Status: Duplicate
