### ISSUE TITLE
Installation fails with PHP 8.0.22 on windows

### ISSUE THREAD

**Issue by Lovor01** [WordPress/WordPress-Coding-Standards#2147] opened 2022-12-10 21:53 UTC
## Bug Description
Installation of php_codesniffer fails with this error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer[v0.5.0, ..., v0.6.2] require php ^5.3|^7 -> your php version (8.0.22) does not satisfy that requirement.    
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5 || ^0.6 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0, v0.6.0, v0.6.1, v0.6.2].
```

## Minimal Code Snippet

The issue happens when running this command:
`composer create-project wp-coding-standards/wpcs --no-dev`

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 8.0.22
| composer                | 2.4.4
| Windows                 | 10

## Tested Against `develop` branch?
- [x ] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment] 2022-12-11 03:20
Closing as a duplicate of #1979, #2000, #2068, #2111.

Please search existing (open and closed) issues before opening a new issue.

**Closed by jrfnl** 2022-12-11 03:20 UTC
Labels: Status: Duplicate
