### ISSUE TITLE
GlobalVariableOverride — Whither `setup_postdata( $post )`?

### ISSUE THREAD

**Issue by taupecat** [WordPress/WordPress-Coding-Standards#1484] opened 2018-09-12 15:01 UTC
I don't know if this is the right place to ask this question, but I'm not sure where else would be better…

When I ran `composer update` on our (rather large, soon to launch) project yesterday, it upgraded my WPCS to version 1.1.0. Now I'm getting a whole _slew_ of errors wherever we've overridden the `$post` global variable to use with `setup_postdata()`. But as we all know, that function _requires_ the variable to be named `$post`; it doesn't accept any other variable name.

So now I'm at a loss as to what to do. While I _could_ rewrite things to create a custom query instead, and thus get around having to use `setup_postdata()` at all, that's not really practical for a couple of reasons:

- Did I mention this is a _large_ project in which most of the development work has been completed and we're within weeks of launch? We don't have the hours to go back and recode everything. Most of the other developers have rolled off the project and I'm just here cleaning up all the loose ends. (This is a pretty big loose end, though.)
- Many of the posts in question are being returned by Advanced Custom Fields. We already have the post object we need; to perform _another_ query would be a hit on performance. (Yes, page and object caching, but still, why run a query when you already have the post object you need?)

I get the theory behind the rule, and it makes _a ton_ of sense. Overriding global variables is bad, agreed. But what I want to know is what does this mean for using `setup_postdata()` in the future? What (if any) is the new best practice?

(For now, I've just turned off that rule so my `gulp` process stops barking at me. But in the future, I want to code to the standards, and if this is the new standard, I'd like to know how to best work with it.)

Thanks for the help.

**Comment by cmcin** [comment] 2018-09-12 15:15
I'm in a similar position. I like the new rule that stops me from accidentally overriding WP variables (like `$path` and `$link`) but for `setup_postdata()` it seems like an exception should have been added.

With that being said, `setup_postdata()` was being a little weird on me for a while so I am trying to move away from it where I can.

I'm interested to see what the response is to this!

**Comment by taupecat** [comment] 2018-09-12 18:48
Well, that's _kinda_ what I'm doing by excluding that one particular rule.
But I think the broader question is still valid: If overwriting global variables like `$post` is bad practice, how _do_ we handle using the `setup_postdata()` function going forward?

**Comment by johnbillion** [comment] 2018-09-28 10:56
This is a duplicate of #842.

**Comment by jrfnl** [comment] 2022-12-09 15:52
Closing as duplicate, let's keep the conversation in one place.

**Closed by jrfnl** 2022-12-09 15:52 UTC
Labels: Status: Duplicate
