### ISSUE TITLE
Switch Dependency from squizlabs/php_codesniffer to PHPCSStandards/PHP_CodeSniffer

### ISSUE THREAD

**Issue by kopepasah** [WordPress/WordPress-Coding-Standards#2425] opened 2024-02-22 20:15 UTC
## Rationale

With the [official abandonment of the `squizlabs/php_codesniffer` project](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932), the WPCS repository must plan to switch the dependency to the new official home of the PHPCS repository: [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer/)

## References
 
 - https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

## Action Checklist

- [ ] ...

**Comment by kopepasah** [comment] 2024-02-22 20:20
I am uncertain what items belong in the Action Checklist. From a quick review, I can see that the `PHPCSStandards/PHP_CodeSniffer` project is still publishing its package to [squizlabs/php_codesniffer](https://packagist.org/packages/squizlabs/), so there could be no action required. 

However, since the squizlabs project is abandoned, it may be benficial (if not at least clearer) that the package is no longer maintained by squizlabs.

**Comment by jrfnl** [comment] 2024-02-22 20:26
Closing as duplicate of something which has already been handled. See #2408

Please search before opening issues. Oh and in this case: please read the [actual announcement](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932) + the release notes of the [PHPCS 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0) and don't open tickets like this is other repos. This ticket is just noise which will confuse people with misinformation.

**Closed by jrfnl** 2024-02-22 20:26 UTC
Labels: Status: Duplicate

**Comment by jrfnl** [comment] 2024-02-22 21:43
FWIW developers who don't read release notes would never have heard about the repo take over anyway, so that is a non-issue.

And I don't see any "misleading information"in the announcement ? You mean it is not clear that a stricken through message accompanied with a clearly marked update in bold, means that information which was in the original announcement was superseded five days later ? Not sure how that could be made clearer.

Not sure what should be communicated about this in this repo's docs, but feel free to submit a pull request if you think things can be improved...
