### ISSUE TITLE
Discourage date() in favor of gmdate()

### ISSUE THREAD

**Issue by Rarst** [WordPress/WordPress-Coding-Standards#1713] opened 2019-05-27 13:50 UTC
## Is your feature request related to a problem?

WordPress core sets PHP time zone to UTC during boot. However it cannot guarantee that timezone isn't changed by third party code, which is relatively common in the wild.

`date()` calls rely on current PHP time zone. If time zone is changed from UTC it causes invalid results through the core and extensions code.

## Describe the solution you'd like

`date()` function should be discouraged in favor of `gmdate()`, which is functionally equivalent, but always operates in UTC and is not affected by runtime time zone changes.

## Additional context

WordPress core code had been recently switched from `date()` to `gmdate()`, see [#46438](https://core.trac.wordpress.org/ticket/46438)

**Comment by jrfnl** [comment] 2019-05-28 00:44
Loosely related to #739

**Comment by jrfnl** [comment] 2019-05-29 12:18
Oops... forgot to mention I opened a PR for this #1714 - @Rarst could you have a look to see if that's in line with your ideas ?

**Comment by Rarst** [comment] 2019-05-29 12:44
Looks good to me. Note that core still has few lingering uses of `date()`, in third party-ish parts. Don't know if there is automated testing being done in core that would trip over it.

**Comment by jrfnl** [comment] 2019-05-29 12:51
Thanks for having a look.

Third party libraries in core are excluded from the WPCS check, so that shouldn't be a problem: https://core.trac.wordpress.org/browser/trunk/phpcs.xml.dist#L78

**Comment by jrfnl** [comment] 2019-09-27 16:06
Ok, so I've just ran into a bug caused by changing a call to `date()` to `gmdate()`.

When working with hard-coded times, like when creating a time dropdown, `date()` should be used over `gmdate()`.

For an example of what I mean, see: https://3v4l.org/MaDQ5

With this in mind, I think we should downgrade it from an `error` to a `warning` as "blindly" changing the function call over can have unintended consequences.

**Comment by Rarst** [comment] 2019-09-27 16:16
You are using `date_default_timezone_set()`, that should not happen in WP environment.

WP core code should _never_ do this. Extension code _might_, but it's a bad idea (for the WP context) and it's on them to justify using `date()` in that case.

**Comment by jrfnl** [comment] 2019-09-27 16:56
@Rarst Of course `date_default_timezone_set()` shouldn't be used, but isn't that the whole point ?
Using `gmdate()` instead of `date()` hardens WP against those situation when it is used. Except that in a limited set of circumstances this may have an undesired side-effect.

**Comment by Rarst** [comment] 2019-09-27 17:24
Maybe I am not following your point? Could you please elaborate on what do you think bug is?

Because `gmdate()` behaving differently from `date()` if you change time zone from UTC is the _feature_ here.

**Comment by jrfnl** [comment] 2019-10-05 08:04
> Because gmdate() behaving differently from date() if you change time zone from UTC is the feature here.

But it's also the reason for the bug when using hard-coded time values.

There are two things I can think of here to mitigate it:
1. Downgrade the `error` to a `warning` and possibly adjust the message to make it clearer that the advise cannot be followed blindly.
2. Add additional logic to the sniff trying to determine if a hard-coded date/time is being passed.
    To be fair, I highly doubt that will be very effective as even with a drop-down as per the example above, the time passed is variable as it is created via a loop.

What do you think ?

**Comment by Rarst** [comment] 2019-10-07 06:02
As above I don't understand what are you calling a bug here.

If you rely on combination of `date()` and `date_default_timezone_set()` to produce somethings that is just doing _two_ things wrong, which sort of to add up to "correct-ish" result (that is precisely what we are trying to get rid off in core and beyond).

The actual correct results is to sniff out and do _neither_ of the two.

**Comment by jrfnl** [comment] 2019-11-11 12:37
I'm going to close this issue for now as the original request from the OP has been addressed.

Bugs against this sniff or requests to make it more intelligent should be opened as a new issue.

**Closed by jrfnl** 2019-11-11 12:37 UTC
Labels: Component: Core, Focus: DateTime, Type: Enhancement
