### ISSUE TITLE
Possible false alarm in printf even if using esc_

### ISSUE THREAD

**Issue by TukuToi** [WordPress/WordPress-Coding-Standards#2005] opened 2021-07-29 11:09 UTC
Apologising in advance if this has been reported in past, I was not clear if the exact issue I see has been discussed since there are a number of similar tickets.

This statement in the code throws the "All Output should be run through an escaping function" on `$count`.
`printf( esc_html__( 'We deleted %d spam messages.', 'my-text-domain' ), $count );`
The code is taken from https://codex.wordpress.org/I18n_for_WordPress_Developers#Best_Practices

Is this a false alarm?
It surely seems so to me, since the output _is_ escaped, exactly like the codex recommends.

Please let me know if I got this wrong, happy to close again. But it seems like this could be improved?

**Comment by jrfnl** [comment] 2021-07-29 11:28
Well, `$count` is **not** escaped - it is outside of the call to `esc_html()` -, but it _is_ rendered safe by the use of `%d` in the translatable string.

Accounting for this requires extensive additional logic which hasn't been added yet.

Closing as duplicate of #1870

**Comment by jrfnl** [comment] 2021-07-29 11:29
Note: for the time being, you can either add an ignore annotation or use `(int) $count` to get rid of the notification from the sniff.

**Closed by jrfnl** 2021-07-29 11:28 UTC
Labels: Status: Duplicate

**Comment by TukuToi** [comment] 2021-07-29 13:38
Thanks @jrfnl!

I will dive into adding an ignore annotation.
Time to learn it 👩‍💻
